//로그인, 로그아웃 ,프로필 정보
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_PROFILE = "LOAD_PROFILE";

//비디오 가져오기
export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL";
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST";

//선택한 비디오 가져오기
export const SELECT_VIDEO_REQUEST = " SELECT_VIDEO_REQUEST";
export const SELECT_VIDEO_SUCCESS = " SELECT_VIDEO_SUCCESS";
export const SELECT_VIDEO_FAIL = " SELECT_VIDEO_FAIL";

//채널 디테일 정보 가져오기
export const CHANNEL_DETAILS_REQUEST = "CHANNEL_DETAILS_REQUEST";
export const CHANNEL_DETAILS_SUCCESS = "CHANNEL_DETAILS_SUCCESS";
export const CHANNEL_DETAILS_FAIL = "CHANNEL_DETAILS_FAIL";

//댓글 리스트 가져오기
export const COMMENT_LIST_SUCCESS = "COMMENT_LIST_SUCCESS";
export const COMMENT_LIST_FAIL = "COMMENT_LIST_FAIL";
export const COMMENT_LIST_REQUEST = "COMMENT_LIST_REQUEST";

//공개 댓글 작성
export const CREATE_COMMENT_SUCCESS = "CREATE_COMMENT_SUCCESS";
export const CREATE_COMMENT_FAIL = "CREATE_COMMENT_FAIL";

//구독 여부(구독 / 구독중)
export const SET_SUBSCRIPTION_STATUS = "SET_SUBSCRIPTION_STATUS";

//관련 비디오
export const RELATED_VIDEO_REQUEST = "RELATED_VIDEO_REQUEST";
export const RELATED_VIDEO_SUCCESS = "RELATED_VIDEO_SUCCESS";
export const RELATED_VIDEO_FAIL = "RELATED_VIDEO_FAIL";

//비디오 검색
export const SEARCH_VIDEOS_REQUEST = "SERACH_VIDEOS_REQUEST";
export const SEARCH_VIDEOS_SUCCESS = "SERACH_VIDEOS_SUCCESS";
export const SEARCH_VIDEOS_FAIL = "SERACH_VIDEOS_FAIL";

//구독중인 채녈 가져오기
export const SUBSCRIPTIONS_CHANNEL_REQUEST = "SUBSCRIPTIONS_CHANNEL_REQUEST";
export const SUBSCRIPTIONS_CHANNEL_SUCCESS = "SUBSCRIPTIONS_CHANNEL_SUCCESS";
export const SUBSCRIPTIONS_CHANNEL_FAIL = "SUBSCRIPTIONS_CHANNEL_FAIL";
