export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOG_OUT = "LOG_OUT";
export const LOAD_PROFILE = "LOAD_PROFILE";

export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL";
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST";

export const SELECT_VIDEO_REQUEST = " SELECT_VIDEO_REQUEST";
export const SELECT_VIDEO_SUCCESS = " SELECT_VIDEO_SUCCESS";
export const SELECT_VIDEO_FAIL = " SELECT_VIDEO_FAIL";
